version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: always
    network_mode: host
    volumes:
      - ./config/mosquitto-mqtt:/mosquitto/config/

  web:
      build: .
      restart: always
      container_name: 'blocklyInterface'
      volumes:
        - ./storage:/code/storage
        # ./storage/virtual_usb:/code/virtual_usb #uncomment if not on raspi
        - /media:/code/virtual_usb #for docker on raspi
      network_mode: host
      depends_on:
        - mosquitto