FROM python:3.11
ENV PYTHONUNBUFFERED 1

WORKDIR /code
#COPY blockly/requierements.txt .
COPY blockly/. /code/blockly
RUN pip install -r blockly/requierements.txt

EXPOSE 8000

CMD [ "python", "blockly/manage.py", "runserver", "0.0.0.0:8000"]
